### ISSUE TITLE
SecretKey decapsulation in Flutter environment

### ISSUE THREAD

**Issue by keybob2048** [juanmadm88/custom_post_quantum#1]
Hello,

I've implemented your code in my flutter application, but unfortunately I'm running into a problem I can't figure out.

```
var kyber = Kyber.kem512();

// Define a key generation seed.
var seed = base64Decode("AAECAwQFBgcICQoLDA0ODwABAgMEBQYHCAkKCwwNDg8AAQIDBAUGBwgJCgsMDQ4PAAECAwQFBgcICQoLDA0ODw==");

// Generate keys from seed.
var (pk, sk) = kyber.generateKeys(seed);

// Define a KEM nonce.
var nonce = base64Decode("Dw8ODg0NDAwLCwoKCQkICAcHBgYFBQQEAwMCAgEBAAA=");

// Encapsulate nonce and retrieve cipher and shared key.
var (cipher, sharedKey1) = kyber.encapsulate(pk, nonce);
print("sharedKey1 : ${base64Encode(sharedKey1)}");

// Or decapsulate the cipher and retrieve the shared key.
var sharedKey2 = kyber.decapsulate(cipher, sk);
print("sharedKey2 : ${base64Encode(sharedKey2)}");
```

On dart, it seems to work correctly, when one decrypts the cipher, the shared key is found.
```
sharedKey1 : qFcluYY42P2U1RoHKJBJSB/R1ZcxXi0rTNoURVRX/Mg=
sharedKey2 : qFcluYY42P2U1RoHKJBJSB/R1ZcxXi0rTNoURVRX/Mg=
```

On the dart flutter environment, the decryption doesn't work as expected. For an IDENTICAL code, we get a different result. Decryption fails to find the shared key.
```
sharedKey1 : FCOXMFU8rXKSKLSdGaYdZuauglSEAWRRQXC+QbvDO2g=
sharedKey2 : r/WkqLJZeo+M8RbvEDgCiNIeCeCJnmS3OxBr5MpBdIs=
```

**Comment by juanmadm88** [comment]
Hello, how are you ?
I'm having the same problem as you.
I can't figure out what's the problem, actually.
I would appreciate any help

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: keybob ***@***.***>
Sent: Monday, September 2, 2024 4:20:17 AM
To: juanmadm88/custom_post_quantum ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [juanmadm88/custom_post_quantum] SecretKey decapsulation in Flutter environment (Issue #1)


Hello,

I've implemented your code in my flutter application, but unfortunately I'm running into a problem I can't figure out.

var kyber = Kyber.kem512();

// Define a key generation seed.
var seed = base64Decode("AAECAwQFBgcICQoLDA0ODwABAgMEBQYHCAkKCwwNDg8AAQIDBAUGBwgJCgsMDQ4PAAECAwQFBgcICQoLDA0ODw==");

// Generate keys from seed.
var (pk, sk) = kyber.generateKeys(seed);

// Define a KEM nonce.
var nonce = base64Decode("Dw8ODg0NDAwLCwoKCQkICAcHBgYFBQQEAwMCAgEBAAA=");

// Encapsulate nonce and retrieve cipher and shared key.
var (cipher, sharedKey1) = kyber.encapsulate(pk, nonce);
print("sharedKey1 : ${base64Encode(sharedKey1)}");

// Or decapsulate the cipher and retrieve the shared key.
var sharedKey2 = kyber.decapsulate(cipher, sk);
print("sharedKey2 : ${base64Encode(sharedKey2)}");


On dart, it seems to work correctly, when one decrypts the cipher, the shared key is found.

sharedKey1 : qFcluYY42P2U1RoHKJBJSB/R1ZcxXi0rTNoURVRX/Mg=
sharedKey2 : qFcluYY42P2U1RoHKJBJSB/R1ZcxXi0rTNoURVRX/Mg=


On the dart flutter environment, the decryption doesn't work as expected. For an IDENTICAL code, we get a different result. Decryption fails to find the shared key.

sharedKey1 : FCOXMFU8rXKSKLSdGaYdZuauglSEAWRRQXC+QbvDO2g=
sharedKey2 : r/WkqLJZeo+M8RbvEDgCiNIeCeCJnmS3OxBr5MpBdIs=
